site_name: Documentación Centralizada
site_description: Documentación que centraliza toda la documentación del CNAD
site_url: https://cnadnoreste.edu.mx/index.php/acerca-del-cnad-noreste/
repo_url: https://github.com/CNAD-TAM/cnad-docs
repo_name: Documentación CNAD

theme:
  name: material
  language: es
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Inter   
    code: JetBrains Mono
  palette:
    - scheme: default   
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate             
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Modo claro

  features:
    # Navegación
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # Búsqueda
    - search.suggest
    - search.highlight
    # Contenido
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.edit
    - content.tabs.link

nav:
  - Inicio: index.md
  - Cursos:
    - Programación de Sistemas Embebidos PIC:
      - Carta descriptiva: subjects/embedded-systems/index.md
      - Contenido temático: 
        - Sesión 1: subjects/embedded-systems/syllabus/session-1.md
        - Sesión 2: subjects/embedded-systems/syllabus/session-2.md
        - Sesión 3: subjects/embedded-systems/syllabus/session-3.md
        - Sesión 4: subjects/embedded-systems/syllabus/session-4.md
        - Sesión 5: subjects/embedded-systems/syllabus/session-5.md
      - Módulos:
        - Material didáctico: subjects/embedded-systems/modules/module-1.md
        - Instrumentos de evaluación: subjects/embedded-systems/modules/module-2.md
        - Manual del participante: subjects/embedded-systems/modules/module-3.md
        - Flyer: subjects/embedded-systems/modules/module-4.md
    - Entrenamiento de Modelos de Inteligencia Artificial:
      - Carta descriptiva: subjects/ia-models-training/index.md
      - Contenido temático: subjects/ia-models-training/syllabus.md
      - Módulos:
        - Material didáctico: subjects/ia-models-training/modules/module-1.md
        - Instrumentos de evaluación: subjects/ia-models-training/modules/module-2.md
        - Manual del participante: subjects/ia-models-training/modules/module-3.md
        - Flyer: subjects/ia-models-training/modules/module-4.md
    - Internet de las cosas:
      - Carta descriptiva: subjects/internet-of-things/index.md
      - Contenido temático: subjects/internet-of-things/syllabus.md
      - Módulos:
        - Material didáctico: subjects/internet-of-things/modules/module-1.md
        - Instrumentos de evaluación: subjects/internet-of-things/modules/module-2.md
        - Manual del participante: subjects/internet-of-things/modules/module-3.md
        - Flyer: subjects/internet-of-things/modules/module-4.md
    - Desarrollo de Software utilizando la metodología ágil Scrum:
      - Carta descriptiva: subjects/scrum-agile/index.md
      - Contenido temático: subjects/scrum-agile/syllabus.md
      - Módulos:
        - Material didáctico: subjects/scrum-agile/modules/module-1.md
        - Instrumentos de evaluación: subjects/scrum-agile/modules/module-2.md
        - Manual del participante: subjects/scrum-agile/modules/module-3.md
        - Flyer: subjects/scrum-agile/modules/module-4.md
    - Sistemas hidráulicos:
      - Carta descriptiva: subjects/hydraulic-systems/index.md
  - Información general: about.md


markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.arithmatex:
      generic: true  
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark

extra:
  homepage: https://docs.cnad.dev
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CNAD-TAM
      name: GitHub • CNAD-TAM
    - icon: material/school
      link: https://cnadnoreste.edu.mx/
      name: CNAD Noreste
  consent:            # opcional: banner de consentimiento sencillo (Analytics)
    title: Cookies & Privacy
    description: We use cookies only to analyze traffic and improve documentation.


extra_javascript:
  - assets/repo-target-blank.js

extra_css:
  - assets/styles/overrides.css   # crea este archivo si quieres retoques finos (opcional)

